import { TAppearance, TBlacklist, TOutfit, TZoneTattoo } from '@typings/apperance';

export const debugAppearance: TAppearance = {
    modelIndex: 0,
    model: 0,
    props: {
        glasses: {
            index: 1,
            id: 'glasses',
            texture: -1,
            value: -1,
        },
        hats: {
            index: 0,
            id: 'hats',
            texture: -1,
            value: -1,
        },
        lhand: {
            index: 4,
            id: 'lhand',
            texture: -1,
            value: -1,
        },
        bracelets: {
            index: 7,
            id: 'bracelets',
            texture: -1,
            value: -1,
        },
        rhand: {
            index: 5,
            id: 'rhand',
            texture: -1,
            value: -1,
        },
        watches: {
            index: 6,
            id: 'watches',
            texture: -1,
            value: -1,
        },
        earrings: {
            index: 2,
            id: 'earrings',
            texture: -1,
            value: -1,
        },
        mouth: {
            index: 3,
            id: 'mouth',
            texture: -1,
            value: -1,
        },
    },
    propTotal: {
        glasses: {
            id: 'glasses',
            index: 1,
            textures: 0,
            total: 42,
        },
        rhand: {
            id: 'rhand',
            index: 5,
            textures: 0,
            total: 0,
        },
        mouth: {
            id: 'mouth',
            index: 3,
            textures: 0,
            total: 0,
        },
        hats: {
            id: 'hats',
            index: 0,
            textures: 0,
            total: 173,
        },
        bracelets: {
            id: 'bracelets',
            index: 7,
            textures: 0,
            total: 10,
        },
        watches: {
            id: 'watches',
            index: 6,
            textures: 0,
            total: 45,
        },
        earrings: {
            id: 'earrings',
            index: 2,
            textures: 0,
            total: 42,
        },
        lhand: {
            id: 'lhand',
            index: 4,
            textures: 0,
            total: 0,
        },
    },
    drawTotal: {
        shirts: {
            id: 'shirts',
            total: 191,
            index: 8,
            textures: 16,
        },
        neck: {
            id: 'neck',
            total: 154,
            index: 7,
            textures: 1,
        },
        shoes: {
            id: 'shoes',
            total: 109,
            index: 6,
            textures: 16,
        },
        bags: {
            id: 'bags',
            total: 111,
            index: 5,
            textures: 1,
        },
        torsos: {
            id: 'torsos',
            total: 198,
            index: 3,
            textures: 1,
        },
        decals: {
            id: 'decals',
            total: 134,
            index: 10,
            textures: 1,
        },
        legs: {
            id: 'legs',
            total: 148,
            index: 4,
            textures: 16,
        },
        jackets: {
            id: 'jackets',
            total: 413,
            index: 11,
            textures: 16,
        },
        hair: {
            id: 'hair',
            total: 79,
            index: 2,
            textures: 1,
        },
        face: {
            id: 'face',
            total: 46,
            index: 0,
            textures: 1,
        },
        masks: {
            id: 'masks',
            total: 209,
            index: 1,
            textures: 1,
        },
        vest: {
            id: 'vest',
            total: 57,
            index: 9,
            textures: 1,
        },
    },
    drawables: {
        masks: {
            id: 'masks',
            texture: 0,
            value: 0,
            index: 1,
        },
        vest: {
            id: 'vest',
            texture: 0,
            value: 0,
            index: 9,
        },
        shirts: {
            id: 'shirts',
            texture: 1,
            value: 0,
            index: 8,
        },
        face: {
            id: 'face',
            texture: 0,
            value: 0,
            index: 0,
        },
        jackets: {
            id: 'jackets',
            texture: 11,
            value: 0,
            index: 11,
        },
        neck: {
            id: 'neck',
            texture: 0,
            value: 0,
            index: 7,
        },
        torsos: {
            id: 'torsos',
            texture: 0,
            value: 0,
            index: 3,
        },
        hair: {
            id: 'hair',
            texture: 0,
            value: 0,
            index: 2,
        },
        legs: {
            id: 'legs',
            texture: 0,
            value: 0,
            index: 4,
        },
        decals: {
            id: 'decals',
            texture: 0,
            value: 0,
            index: 10,
        },
        bags: {
            id: 'bags',
            texture: 0,
            value: 0,
            index: 5,
        },
        shoes: {
            id: 'shoes',
            texture: 2,
            value: 1,
            index: 6,
        },
    },
    headOverlay: {
        Ageing: {
            index: 3,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 0,
            secondColor: 0,
            id: 'Ageing',
            overlayValue: 255,
        },
        BodyBlemishes: {
            index: 11,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 0,
            secondColor: 0,
            id: 'BodyBlemishes',
            overlayValue: 255,
        },
        Blush: {
            index: 5,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 2,
            secondColor: 0,
            id: 'Blush',
            overlayValue: 255,
        },
        Eyebrows: {
            index: 2,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 1,
            secondColor: 0,
            id: 'Eyebrows',
            overlayValue: 255,
        },
        EyeColor: {
            index: 13,
            id: 'EyeColor',
            value: -1,
        },
        ChestHair: {
            index: 10,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 1,
            secondColor: 0,
            id: 'ChestHair',
            overlayValue: 255,
        },
        AddBodyBlemishes: {
            index: 12,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 0,
            secondColor: 0,
            id: 'AddBodyBlemishes',
            overlayValue: 255,
        },
        MolesFreckles: {
            index: 9,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 0,
            secondColor: 0,
            id: 'MolesFreckles',
            overlayValue: 255,
        },
        Lipstick: {
            index: 8,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 2,
            secondColor: 0,
            id: 'Lipstick',
            overlayValue: 255,
        },
        FacialHair: {
            index: 1,
            overlayOpacity: 0,
            firstColor: 0,
            colourType: 1,
            secondColor: 0,
            id: 'FacialHair',
            overlayValue: 255,
        },
        SunDamage: {
            index: 7,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 0,
            secondColor: 0,
            id: 'SunDamage',
            overlayValue: 255,
        },
        Complexion: {
            index: 6,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 0,
            secondColor: 0,
            id: 'Complexion',
            overlayValue: 255,
        },
        Makeup: {
            index: 4,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 2,
            secondColor: 0,
            id: 'Makeup',
            overlayValue: 255,
        },
        Blemishes: {
            index: 0,
            overlayOpacity: 1,
            firstColor: 0,
            colourType: 0,
            secondColor: 0,
            id: 'Blemishes',
            overlayValue: 255,
        },
    },
    hairColor: {
        highlight: 1,
        color: 1,
    },
    headBlend: {
        skinSecond: 0,
        skinThird: 0,
        shapeSecond: 0,
        shapeThird: 0,
        shapeFirst: 0,
        hasParent: false,
        skinMix: 1,
        shapeMix: 0,
        thirdMix: 0,
        skinFirst: 15,
    },
    headStructure: {
        Chin_Bone_Width: {
            index: 17,
            id: 'Chin_Bone_Width',
            value: 0,
        },
        EyeBrown_Forward: {
            index: 7,
            id: 'EyeBrown_Forward',
            value: 0,
        },
        Lips_Thickness: {
            index: 12,
            id: 'Lips_Thickness',
            value: 0,
        },
        Eyes_Openning: {
            index: 11,
            id: 'Eyes_Openning',
            value: 0,
        },
        Cheeks_Width: {
            index: 10,
            id: 'Cheeks_Width',
            value: 0,
        },
        Chin_Bone_Lowering: {
            index: 15,
            id: 'Chin_Bone_Lowering',
            value: 0,
        },
        Jaw_Bone_Back_Lenght: {
            index: 14,
            id: 'Jaw_Bone_Back_Lenght',
            value: 0,
        },
        EyeBrown_Height: {
            index: 6,
            id: 'EyeBrown_Height',
            value: 0,
        },
        Nose_Peak_Lenght: {
            index: 2,
            id: 'Nose_Peak_Lenght',
            value: 0,
        },
        Chin_Bone_Length: {
            index: 16,
            id: 'Chin_Bone_Length',
            value: 0,
        },
        Nose_Bone_Height: {
            index: 3,
            id: 'Nose_Bone_Height',
            value: 0,
        },
        Jaw_Bone_Width: {
            index: 13,
            id: 'Jaw_Bone_Width',
            value: 0,
        },
        Cheeks_Bone_High: {
            index: 8,
            id: 'Cheeks_Bone_High',
            value: 0,
        },
        Neck_Thikness: {
            index: 19,
            id: 'Neck_Thikness',
            value: 0,
        },
        Chin_Hole: {
            index: 18,
            id: 'Chin_Hole',
            value: 0,
        },
        Nose_Peak_Height: {
            index: 1,
            id: 'Nose_Peak_Height',
            value: 0,
        },
        Nose_Peak_Lowering: {
            index: 4,
            id: 'Nose_Peak_Lowering',
            value: 0,
        },
        Cheeks_Bone_Width: {
            index: 9,
            id: 'Cheeks_Bone_Width',
            value: 0,
        },
        Nose_Bone_Twist: {
            index: 5,
            id: 'Nose_Bone_Twist',
            value: 0,
        },
        Nose_Width: {
            index: 0,
            id: 'Nose_Width',
            value: 0,
        },
    },
    headOverlayTotal: {
        Ageing: 15,
        BodyBlemishes: 12,
        Blush: 33,
        Eyebrows: 34,
        EyeColor: 0,
        ChestHair: 17,
        AddBodyBlemishes: 2,
        MolesFreckles: 18,
        Lipstick: 10,
        FacialHair: 29,
        SunDamage: 11,
        Complexion: 12,
        Makeup: 95,
        Blemishes: 24,
    },
    tattoos: [],
};

export const debugOutfits: TOutfit[] = [
    {
        label: 'Outfit 1',
        id: 1,
        outfit: {
            drawables: {
                masks: {
                    id: 'masks',
                    texture: 0,
                    value: 0,
                    index: 1,
                },
                vest: {
                    id: 'vest',
                    texture: 0,
                    value: 0,
                    index: 9,
                },
                shirts: {
                    id: 'shirts',
                    texture: 1,
                    value: 0,
                    index: 8,
                },
                face: {
                    id: 'face',
                    texture: 0,
                    value: 0,
                    index: 0,
                },
                jackets: {
                    id: 'jackets',
                    texture: 11,
                    value: 0,
                    index: 11,
                },
                neck: {
                    id: 'neck',
                    texture: 0,
                    value: 0,
                    index: 7,
                },
                torsos: {
                    id: 'torsos',
                    texture: 0,
                    value: 0,
                    index: 3,
                },
                hair: {
                    id: 'hair',
                    texture: 0,
                    value: 0,
                    index: 2,
                },
                legs: {
                    id: 'legs',
                    texture: 0,
                    value: 0,
                    index: 4,
                },
                decals: {
                    id: 'decals',
                    texture: 0,
                    value: 0,
                    index: 10,
                },
                bags: {
                    id: 'bags',
                    texture: 0,
                    value: 0,
                    index: 5,
                },
                shoes: {
                    id: 'shoes',
                    texture: 2,
                    value: 1,
                    index: 6,
                },
            },
            headOverlay: {
                Ageing: {
                    index: 3,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Ageing',
                    overlayValue: 255,
                },
                BodyBlemishes: {
                    index: 11,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'BodyBlemishes',
                    overlayValue: 255,
                },
                Blush: {
                    index: 5,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Blush',
                    overlayValue: 255,
                },
                Eyebrows: {
                    index: 2,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'Eyebrows',
                    overlayValue: 255,
                },
                EyeColor: {
                    index: 13,
                    id: 'EyeColor',
                    value: -1,
                },
                ChestHair: {
                    index: 10,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'ChestHair',
                    overlayValue: 255,
                },
                AddBodyBlemishes: {
                    index: 12,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'AddBodyBlemishes',
                    overlayValue: 255,
                },
                MolesFreckles: {
                    index: 9,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'MolesFreckles',
                    overlayValue: 255,
                },
                Lipstick: {
                    index: 8,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Lipstick',
                    overlayValue: 255,
                },
                FacialHair: {
                    index: 1,
                    overlayOpacity: 0,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'FacialHair',
                    overlayValue: 255,
                },
                SunDamage: {
                    index: 7,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'SunDamage',
                    overlayValue: 255,
                },
                Complexion: {
                    index: 6,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Complexion',
                    overlayValue: 255,
                },
                Makeup: {
                    index: 4,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Makeup',
                    overlayValue: 255,
                },
                Blemishes: {
                    index: 0,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Blemishes',
                    overlayValue: 255,
                },
            },
            props: {
                glasses: {
                    index: 1,
                    id: 'glasses',
                    texture: -1,
                    value: -1,
                },
                hats: {
                    index: 0,
                    id: 'hats',
                    texture: -1,
                    value: -1,
                },
                lhand: {
                    index: 4,
                    id: 'lhand',
                    texture: -1,
                    value: -1,
                },
                bracelets: {
                    index: 7,
                    id: 'bracelets',
                    texture: -1,
                    value: -1,
                },
                rhand: {
                    index: 5,
                    id: 'rhand',
                    texture: -1,
                    value: -1,
                },
                watches: {
                    index: 6,
                    id: 'watches',
                    texture: -1,
                    value: -1,
                },
                earrings: {
                    index: 2,
                    id: 'earrings',
                    texture: -1,
                    value: -1,
                },
                mouth: {
                    index: 3,
                    id: 'mouth',
                    texture: -1,
                    value: -1,
                },
            },
        },
    },
    {
        label: 'Outfit 2',
        id: 2,
        outfit: {
            drawables: {
                masks: {
                    id: 'masks',
                    texture: 0,
                    value: 0,
                    index: 1,
                },
                vest: {
                    id: 'vest',
                    texture: 0,
                    value: 0,
                    index: 9,
                },
                shirts: {
                    id: 'shirts',
                    texture: 1,
                    value: 0,
                    index: 8,
                },
                face: {
                    id: 'face',
                    texture: 0,
                    value: 0,
                    index: 0,
                },
                jackets: {
                    id: 'jackets',
                    texture: 11,
                    value: 0,
                    index: 11,
                },
                neck: {
                    id: 'neck',
                    texture: 0,
                    value: 0,
                    index: 7,
                },
                torsos: {
                    id: 'torsos',
                    texture: 0,
                    value: 0,
                    index: 3,
                },
                hair: {
                    id: 'hair',
                    texture: 0,
                    value: 0,
                    index: 2,
                },
                legs: {
                    id: 'legs',
                    texture: 0,
                    value: 0,
                    index: 4,
                },
                decals: {
                    id: 'decals',
                    texture: 0,
                    value: 0,
                    index: 10,
                },
                bags: {
                    id: 'bags',
                    texture: 0,
                    value: 0,
                    index: 5,
                },
                shoes: {
                    id: 'shoes',
                    texture: 2,
                    value: 1,
                    index: 6,
                },
            },
            headOverlay: {
                Ageing: {
                    index: 3,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Ageing',
                    overlayValue: 255,
                },
                BodyBlemishes: {
                    index: 11,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'BodyBlemishes',
                    overlayValue: 255,
                },
                Blush: {
                    index: 5,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Blush',
                    overlayValue: 255,
                },
                Eyebrows: {
                    index: 2,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'Eyebrows',
                    overlayValue: 255,
                },
                EyeColor: {
                    index: 13,
                    id: 'EyeColor',
                    value: -1,
                },
                ChestHair: {
                    index: 10,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'ChestHair',
                    overlayValue: 255,
                },
                AddBodyBlemishes: {
                    index: 12,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'AddBodyBlemishes',
                    overlayValue: 255,
                },
                MolesFreckles: {
                    index: 9,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'MolesFreckles',
                    overlayValue: 255,
                },
                Lipstick: {
                    index: 8,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Lipstick',
                    overlayValue: 255,
                },
                FacialHair: {
                    index: 1,
                    overlayOpacity: 0,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'FacialHair',
                    overlayValue: 255,
                },
                SunDamage: {
                    index: 7,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'SunDamage',
                    overlayValue: 255,
                },
                Complexion: {
                    index: 6,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Complexion',
                    overlayValue: 255,
                },
                Makeup: {
                    index: 4,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Makeup',
                    overlayValue: 255,
                },
                Blemishes: {
                    index: 0,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Blemishes',
                    overlayValue: 255,
                },
            },
            props: {
                glasses: {
                    index: 1,
                    id: 'glasses',
                    texture: -1,
                    value: -1,
                },
                hats: {
                    index: 0,
                    id: 'hats',
                    texture: -1,
                    value: -1,
                },
                lhand: {
                    index: 4,
                    id: 'lhand',
                    texture: -1,
                    value: -1,
                },
                bracelets: {
                    index: 7,
                    id: 'bracelets',
                    texture: -1,
                    value: -1,
                },
                rhand: {
                    index: 5,
                    id: 'rhand',
                    texture: -1,
                    value: -1,
                },
                watches: {
                    index: 6,
                    id: 'watches',
                    texture: -1,
                    value: -1,
                },
                earrings: {
                    index: 2,
                    id: 'earrings',
                    texture: -1,
                    value: -1,
                },
                mouth: {
                    index: 3,
                    id: 'mouth',
                    texture: -1,
                    value: -1,
                },
            },
        },
    },
    {
        label: 'Outfit 3',
        id: 2,
        outfit: {
            drawables: {
                masks: {
                    id: 'masks',
                    texture: 0,
                    value: 0,
                    index: 1,
                },
                vest: {
                    id: 'vest',
                    texture: 0,
                    value: 0,
                    index: 9,
                },
                shirts: {
                    id: 'shirts',
                    texture: 1,
                    value: 0,
                    index: 8,
                },
                face: {
                    id: 'face',
                    texture: 0,
                    value: 0,
                    index: 0,
                },
                jackets: {
                    id: 'jackets',
                    texture: 11,
                    value: 0,
                    index: 11,
                },
                neck: {
                    id: 'neck',
                    texture: 0,
                    value: 0,
                    index: 7,
                },
                torsos: {
                    id: 'torsos',
                    texture: 0,
                    value: 0,
                    index: 3,
                },
                hair: {
                    id: 'hair',
                    texture: 0,
                    value: 0,
                    index: 2,
                },
                legs: {
                    id: 'legs',
                    texture: 0,
                    value: 0,
                    index: 4,
                },
                decals: {
                    id: 'decals',
                    texture: 0,
                    value: 0,
                    index: 10,
                },
                bags: {
                    id: 'bags',
                    texture: 0,
                    value: 0,
                    index: 5,
                },
                shoes: {
                    id: 'shoes',
                    texture: 2,
                    value: 1,
                    index: 6,
                },
            },
            headOverlay: {
                Ageing: {
                    index: 3,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Ageing',
                    overlayValue: 255,
                },
                BodyBlemishes: {
                    index: 11,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'BodyBlemishes',
                    overlayValue: 255,
                },
                Blush: {
                    index: 5,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Blush',
                    overlayValue: 255,
                },
                Eyebrows: {
                    index: 2,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'Eyebrows',
                    overlayValue: 255,
                },
                EyeColor: {
                    index: 13,
                    id: 'EyeColor',
                    value: -1,
                },
                ChestHair: {
                    index: 10,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'ChestHair',
                    overlayValue: 255,
                },
                AddBodyBlemishes: {
                    index: 12,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'AddBodyBlemishes',
                    overlayValue: 255,
                },
                MolesFreckles: {
                    index: 9,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'MolesFreckles',
                    overlayValue: 255,
                },
                Lipstick: {
                    index: 8,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Lipstick',
                    overlayValue: 255,
                },
                FacialHair: {
                    index: 1,
                    overlayOpacity: 0,
                    firstColor: 0,
                    colourType: 1,
                    secondColor: 0,
                    id: 'FacialHair',
                    overlayValue: 255,
                },
                SunDamage: {
                    index: 7,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'SunDamage',
                    overlayValue: 255,
                },
                Complexion: {
                    index: 6,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Complexion',
                    overlayValue: 255,
                },
                Makeup: {
                    index: 4,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 2,
                    secondColor: 0,
                    id: 'Makeup',
                    overlayValue: 255,
                },
                Blemishes: {
                    index: 0,
                    overlayOpacity: 1,
                    firstColor: 0,
                    colourType: 0,
                    secondColor: 0,
                    id: 'Blemishes',
                    overlayValue: 255,
                },
            },
            props: {
                glasses: {
                    index: 1,
                    id: 'glasses',
                    texture: -1,
                    value: -1,
                },
                hats: {
                    index: 0,
                    id: 'hats',
                    texture: -1,
                    value: -1,
                },
                lhand: {
                    index: 4,
                    id: 'lhand',
                    texture: -1,
                    value: -1,
                },
                bracelets: {
                    index: 7,
                    id: 'bracelets',
                    texture: -1,
                    value: -1,
                },
                rhand: {
                    index: 5,
                    id: 'rhand',
                    texture: -1,
                    value: -1,
                },
                watches: {
                    index: 6,
                    id: 'watches',
                    texture: -1,
                    value: -1,
                },
                earrings: {
                    index: 2,
                    id: 'earrings',
                    texture: -1,
                    value: -1,
                },
                mouth: {
                    index: 3,
                    id: 'mouth',
                    texture: -1,
                    value: -1,
                },
            },
        },
    },
];

export const debugTattoos: TZoneTattoo[] = [
    {
        label: 'Torso',
        dlcs: [
            {
                tattoos: [],
                dlcIndex: 0,
                label: 'mpbeach_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Christmas2017_Tattoo_000_M',
                        hash: 388715677,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_002_M',
                        hash: -1233846590,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_003_M',
                        hash: -1448569917,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_005_M',
                        hash: 1945550351,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_008_M',
                        hash: -416717212,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_009_M',
                        hash: -1228169566,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_010_M',
                        hash: 1472355612,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_011_M',
                        hash: 19369937,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_015_M',
                        hash: -1531355431,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_016_M',
                        hash: 2040691909,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_019_M',
                        hash: 946610385,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_020_M',
                        hash: 1384666834,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_021_M',
                        hash: -1850499077,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_022_M',
                        hash: 1599340952,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_024_M',
                        hash: 1896039464,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_026_M',
                        hash: -861144593,
                        zone: 0,
                    },
                    {
                        label: 'MP_Christmas2017_Tattoo_027_M',
                        hash: -29907878,
                        zone: 0,
                    },
                ],
                dlcIndex: 1,
                label: 'mpchristmas2017_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Christmas2018_Tat_000_M',
                        hash: 450544862,
                        zone: 0,
                    },
                ],
                dlcIndex: 2,
                label: 'mpchristmas2018_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_LUXE_TAT_002_M',
                        hash: 907364848,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_012_M',
                        hash: -938326281,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_022_M',
                        hash: 1232639216,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_025_M',
                        hash: 816551665,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_027_M',
                        hash: -796818724,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_029_M',
                        hash: 266230635,
                        zone: 0,
                    },
                ],
                dlcIndex: 3,
                label: 'mpluxe2_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_LUXE_TAT_003_M',
                        hash: 1027059614,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_006_M',
                        hash: 216134256,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_007_M',
                        hash: 810154442,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_008_M',
                        hash: 77285961,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_014_M',
                        hash: 711811694,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_015_M',
                        hash: -895106351,
                        zone: 0,
                    },
                    {
                        label: 'MP_LUXE_TAT_024_M',
                        hash: -866958715,
                        zone: 0,
                    },
                ],
                dlcIndex: 4,
                label: 'mpluxe_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Smuggler_Tattoo_002_M',
                        hash: -439062355,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_003_M',
                        hash: -187785912,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_006_M',
                        hash: -1071879097,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_007_M',
                        hash: 2048147896,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_009_M',
                        hash: -1811149087,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_010_M',
                        hash: -256036523,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_013_M',
                        hash: 181399885,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_015_M',
                        hash: 928781515,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_016_M',
                        hash: -1757440846,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_017_M',
                        hash: -887356639,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_018_M',
                        hash: -162415909,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_019_M',
                        hash: -1822176783,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_021_M',
                        hash: -969415240,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_022_M',
                        hash: 1482211094,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_024_M',
                        hash: 1376322385,
                        zone: 0,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_025_M',
                        hash: 1678423640,
                        zone: 0,
                    },
                ],
                dlcIndex: 5,
                label: 'mpsmuggler_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_MP_Stunt_Tat_011_M',
                        hash: -1964967283,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_012_M',
                        hash: -1635180127,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_014_M',
                        hash: 933419071,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_018_M',
                        hash: -1817642831,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_019_M',
                        hash: 482472119,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_024_M',
                        hash: -1719543542,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_026_M',
                        hash: -2018029706,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_027_M',
                        hash: -717212544,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_029_M',
                        hash: 1520437442,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_030_M',
                        hash: 374349467,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_033_M',
                        hash: 130721536,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_034_M',
                        hash: 195356001,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_037_M',
                        hash: 941227127,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_040_M',
                        hash: 224191803,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_041_M',
                        hash: -1996796255,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_044_M',
                        hash: 1567227108,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_046_M',
                        hash: -25727072,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_048_M',
                        hash: 1878229535,
                        zone: 0,
                    },
                ],
                dlcIndex: 6,
                label: 'mpstunt_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'FM_Tat_Award_M_003',
                        hash: 1369179057,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_004',
                        hash: 1708731435,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_005',
                        hash: -2038633110,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_008',
                        hash: 1880932522,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_011',
                        hash: -1891729451,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_012',
                        hash: 2024821433,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_013',
                        hash: 1404700877,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_014',
                        hash: 1160735672,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_016',
                        hash: -667086347,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_017',
                        hash: -1781887727,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_018',
                        hash: -1542968948,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_Award_M_019',
                        hash: 23192638,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_004',
                        hash: -1912858770,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_009',
                        hash: 301211484,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_010',
                        hash: 1091893813,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_011',
                        hash: 726093466,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_012',
                        hash: 420522541,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_013',
                        hash: 129664897,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_016',
                        hash: 1391336935,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_019',
                        hash: 1180435659,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_011',
                        hash: 726093466,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_012',
                        hash: 420522541,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_013',
                        hash: 129664897,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_016',
                        hash: 1391336935,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_020',
                        hash: -1835950503,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_024',
                        hash: -820013196,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_025',
                        hash: 95192205,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_029',
                        hash: -1157009596,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_030',
                        hash: -189671992,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_034',
                        hash: 701448198,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_036',
                        hash: -978683978,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_044',
                        hash: 1544332704,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_045',
                        hash: -1830055079,
                        zone: 0,
                    },
                    {
                        label: 'FM_Tat_M_046',
                        hash: -927596819,
                        zone: 0,
                    },
                ],
                dlcIndex: 7,
                label: 'multiplayer_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 8,
                label: 'mphipster_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 9,
                label: 'mpbiker_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Airraces_Tattoo_000_M',
                        hash: -1477471726,
                        zone: 0,
                    },
                    {
                        label: 'MP_Airraces_Tattoo_001_M',
                        hash: -650926235,
                        zone: 0,
                    },
                    {
                        label: 'MP_Airraces_Tattoo_002_M',
                        hash: -618318124,
                        zone: 0,
                    },
                    {
                        label: 'MP_Airraces_Tattoo_004_M',
                        hash: -1532633409,
                        zone: 0,
                    },
                    {
                        label: 'MP_Airraces_Tattoo_005_M',
                        hash: 1605199232,
                        zone: 0,
                    },
                    {
                        label: 'MP_Airraces_Tattoo_006_M',
                        hash: 113768799,
                        zone: 0,
                    },
                    {
                        label: 'MP_Airraces_Tattoo_007_M',
                        hash: -267657422,
                        zone: 0,
                    },
                ],
                dlcIndex: 10,
                label: 'mpairraces_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Bea_M_Back_000',
                        hash: 1056297333,
                        zone: 0,
                    },
                    {
                        label: 'MP_Bea_M_Chest_000',
                        hash: 494620709,
                        zone: 0,
                    },
                    {
                        label: 'MP_Bea_M_Chest_001',
                        hash: 800453786,
                        zone: 0,
                    },
                    {
                        label: 'MP_Bea_M_Stom_000',
                        hash: -1801855538,
                        zone: 0,
                    },
                    {
                        label: 'MP_Bea_M_Stom_001',
                        hash: -904148779,
                        zone: 0,
                    },
                ],
                dlcIndex: 11,
                label: 'mpbeach_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Xmas2_M_Tat_005',
                        hash: -633330920,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_006',
                        hash: -308131364,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_009',
                        hash: 929455459,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_011',
                        hash: 1904300216,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_013',
                        hash: -1897002095,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_015',
                        hash: -1316794181,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_016',
                        hash: -416105443,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_017',
                        hash: -47978497,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_018',
                        hash: -358202620,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_019',
                        hash: 547139312,
                        zone: 0,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_028',
                        hash: 1630543134,
                        zone: 0,
                    },
                ],
                dlcIndex: 12,
                label: 'mpchristmas2_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Gunrunning_Tattoo_000_M',
                        hash: 133895676,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_001_M',
                        hash: -2040228203,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_009_M',
                        hash: -1365916084,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_010_M',
                        hash: -422913369,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_012_M',
                        hash: -1795208156,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_013_M',
                        hash: 573261452,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_014_M',
                        hash: 2111374302,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_017_M',
                        hash: -54254731,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_018_M',
                        hash: 112211142,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_019_M',
                        hash: 1306824915,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_020_M',
                        hash: -1841627189,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_022_M',
                        hash: -46260381,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_028_M',
                        hash: 1082588124,
                        zone: 0,
                    },
                    {
                        label: 'MP_Gunrunning_Tattoo_029_M',
                        hash: -457752320,
                        zone: 0,
                    },
                ],
                dlcIndex: 13,
                label: 'mpgunrunning_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_MP_ImportExport_Tat_000_M',
                        hash: -504012739,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_ImportExport_Tat_001_M',
                        hash: 34276608,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_ImportExport_Tat_002_M',
                        hash: -2088223199,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_ImportExport_Tat_009_M',
                        hash: -1862916472,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_ImportExport_Tat_010_M',
                        hash: -1184732039,
                        zone: 0,
                    },
                    {
                        label: 'MP_MP_ImportExport_Tat_011_M',
                        hash: -143503455,
                        zone: 0,
                    },
                ],
                dlcIndex: 14,
                label: 'mpimportexport_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 15,
                label: 'mplowrider2_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 16,
                label: 'mplowrider_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'mpHeist3_Tat_023_M',
                        hash: -1150178569,
                        zone: 0,
                    },
                ],
                dlcIndex: 17,
                label: 'mpheist3_overlays',
            },
        ],
        zoneIndex: 0,
        zone: 'ZONE_TORSO',
    },
    {
        label: 'Head',
        dlcs: [
            {
                tattoos: [],
                dlcIndex: 0,
                label: 'mpbeach_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 1,
                label: 'mpchristmas2017_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 2,
                label: 'mpchristmas2018_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 3,
                label: 'mpluxe2_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 4,
                label: 'mpluxe_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Smuggler_Tattoo_011_M',
                        hash: -247186222,
                        zone: 1,
                    },
                    {
                        label: 'MP_Smuggler_Tattoo_012_M',
                        hash: -355946577,
                        zone: 1,
                    },
                ],
                dlcIndex: 5,
                label: 'mpsmuggler_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_MP_Stunt_Tat_000_M',
                        hash: 1570835960,
                        zone: 1,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_004_M',
                        hash: 220143168,
                        zone: 1,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_006_M',
                        hash: -773345516,
                        zone: 1,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_017_M',
                        hash: -1869054624,
                        zone: 1,
                    },
                    {
                        label: 'MP_MP_Stunt_Tat_042_M',
                        hash: -1850715440,
                        zone: 1,
                    },
                ],
                dlcIndex: 6,
                label: 'mpstunt_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'FM_Tat_Award_M_000',
                        hash: 420418200,
                        zone: 1,
                    },
                ],
                dlcIndex: 7,
                label: 'multiplayer_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 8,
                label: 'mphipster_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 9,
                label: 'mpbiker_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 10,
                label: 'mpairraces_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Bea_M_Head_000',
                        hash: -1082736975,
                        zone: 1,
                    },
                    {
                        label: 'MP_Bea_M_Head_001',
                        hash: -754981437,
                        zone: 1,
                    },
                    {
                        label: 'MP_Bea_M_Head_002',
                        hash: 164352862,
                        zone: 1,
                    },
                    {
                        label: 'MP_Bea_M_Head_000',
                        hash: -1082736975,
                        zone: 1,
                    },
                    {
                        label: 'MP_Bea_M_Neck_000',
                        hash: -221624488,
                        zone: 1,
                    },
                    {
                        label: 'MP_Bea_M_Neck_001',
                        hash: 25158851,
                        zone: 1,
                    },
                ],
                dlcIndex: 11,
                label: 'mpbeach_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Xmas2_M_Tat_007',
                        hash: -38278649,
                        zone: 1,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_024',
                        hash: 1121411181,
                        zone: 1,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_025',
                        hash: 890225886,
                        zone: 1,
                    },
                    {
                        label: 'MP_Xmas2_M_Tat_029',
                        hash: -1945668916,
                        zone: 1,
                    },
                ],
                dlcIndex: 12,
                label: 'mpchristmas2_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'MP_Gunrunning_Tattoo_003_M',
                        hash: 291473683,
                        zone: 1,
                    },
                ],
                dlcIndex: 13,
                label: 'mpgunrunning_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 14,
                label: 'mpimportexport_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 15,
                label: 'mplowrider2_overlays',
            },
            {
                tattoos: [],
                dlcIndex: 16,
                label: 'mplowrider_overlays',
            },
            {
                tattoos: [
                    {
                        label: 'mpHeist3_Tat_000_M',
                        hash: 1048452439,
                        zone: 1,
                    },
                ],
                dlcIndex: 17,
                label: 'mpheist3_overlays',
            },
        ],
        zoneIndex: 1,
        zone: 'ZONE_HEAD',
    },
];

export const debugBlacklist: TBlacklist = {
    models: [],
	drawables: {},
	props: {},
}

export const debugModels = [
    'mp_m_freemode_01',
    'mp_f_freemode_01',
    'a_f_m_beach_01',
    'a_f_m_bevhills_01',
    'a_f_m_bevhills_02',
    'a_f_m_bodybuild_01',
    'a_f_m_business_02',
    'a_f_m_downtown_01',
    'a_f_m_eastsa_01',
    'a_f_m_eastsa_02',
    'a_f_m_fatbla_01',
    'a_f_m_fatcult_01',
    'a_f_m_fatwhite_01',
    'a_f_m_ktown_01',
    'a_f_m_ktown_02',
    'a_f_m_prolhost_01',
    'a_f_m_salton_01',
    'a_f_m_skidrow_01',
    'a_f_m_soucent_01',
    'a_f_m_soucent_02',
    'a_f_m_soucentmc_01',
    'a_f_m_tourist_01',
    'a_f_m_tramp_01',
    'a_f_m_trampbeac_01',
    'a_f_o_genstreet_01',
    'a_f_o_indian_01',
    'a_f_o_ktown_01',
    'a_f_o_salton_01',
    'a_f_o_soucent_01',
    'a_f_o_soucent_02',
    'a_f_y_beach_01',
    'a_f_y_bevhills_01',
    'a_f_y_bevhills_02',
    'a_f_y_bevhills_03',
    'a_f_y_bevhills_04',
    'a_f_y_business_01',
    'a_f_y_business_02',
    'a_f_y_business_03',
    'a_f_y_business_04',
    'a_f_y_eastsa_01',
    'a_f_y_eastsa_02',
    'a_f_y_eastsa_03',
    'a_f_y_epsilon_01',
    'a_f_y_femaleagent',
    'a_f_y_fitness_01',
    'a_f_y_fitness_02',
    'a_f_y_genhot_01',
    'a_f_y_golfer_01',
    'a_f_y_hiker_01',
    'a_f_y_hippie_01',
    'a_f_y_hipster_01',
    'a_f_y_hipster_02',
    'a_f_y_hipster_03',
    'a_f_y_hipster_04',
    'a_f_y_indian_01',
    'a_f_y_juggalo_01',
    'a_f_y_runner_01',
    'a_f_y_rurmeth_01',
    'a_f_y_scdressy_01',
    'a_f_y_skater_01',
    'a_f_y_soucent_01',
    'a_f_y_soucent_02',
    'a_f_y_soucent_03',
    'a_f_y_tennis_01',
    'a_f_y_topless_01',
    'a_f_y_tourist_01',
    'a_f_y_tourist_02',
    'a_f_y_vinewood_01',
    'a_f_y_vinewood_02',
    'a_f_y_vinewood_03',
    'a_f_y_vinewood_04',
    'a_f_y_yoga_01',
    'a_m_m_acult_01',
    'a_m_m_afriamer_01',
    'a_m_m_beach_01',
    'a_m_m_beach_02',
    'a_m_m_bevhills_01',
    'a_m_m_bevhills_02',
    'a_m_m_business_01',
    'a_m_m_eastsa_01',
    'a_m_m_eastsa_02',
    'a_m_m_farmer_01',
    'a_m_m_fatlatin_01',
    'a_m_m_genfat_01',
    'a_m_m_genfat_02',
    'a_m_m_golfer_01',
    'a_m_m_hasjew_01',
    'a_m_m_hillbilly_01',
    'a_m_m_hillbilly_02',
    'a_m_m_indian_01',
    'a_m_m_ktown_01',
    'a_m_m_malibu_01',
    'a_m_m_mexcntry_01',
    'a_m_m_mexlabor_01',
    'a_m_m_og_boss_01',
    'a_m_m_paparazzi_01',
    'a_m_m_polynesian_01',
    'a_m_m_prolhost_01',
    'a_m_m_rurmeth_01',
    'a_m_m_salton_01',
    'a_m_m_salton_02',
    'a_m_m_salton_03',
    'a_m_m_salton_04',
    'a_m_m_skater_01',
]